spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

logging:
  level:
    vn.dcid: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
